{
  lib,
  stdenv,
  appimageTools,
  fetchurl,
  makeDesktopItem,
  myPkgs,
}:

let
  # Generated by ./update.sh
  info = (lib.importJSON ./input.json).${stdenv.hostPlatform.system};

  src = fetchurl {
    name = "zalo-${info.version}.AppImage";
    inherit (info) url sha256;
  };

  desktopItem = makeDesktopItem {
    name = "zalo";
    desktopName = "Zalo";
    genericName = "Instant Messenger";
    comment = "Zalo for Linux";
    exec = "zalo %U";
    icon = "zalo";
    terminal = false;
    categories = [
      "Network"
      "InstantMessaging"
    ];
    startupWMClass = "Zalo";
  };
in
appimageTools.wrapType2 {
  pname = "zalo";
  inherit (info) version;
  inherit src;

  # Image paste from the clipboard shells out to these.
  extraPkgs = pkgs: [
    pkgs.wl-clipboard
    pkgs.xclip
    pkgs.nspr
    pkgs.nss
    pkgs.atk
    pkgs.at-spi2-atk
    pkgs.libdrm
    pkgs.mesa
    pkgs.gtk3
    pkgs.pango
    pkgs.cairo
    pkgs.gdk-pixbuf
    pkgs.glib
    pkgs.dbus
    pkgs.expat
    pkgs.libxkbcommon
    pkgs.alsa-lib
    pkgs.cups
    pkgs.libglvnd
  ];

  extraInstallCommands = ''
    install -Dm644 ${myPkgs.assets}/icons/zalo.png $out/share/pixmaps/zalo.png
    install -Dm644 ${desktopItem}/share/applications/zalo.desktop $out/share/applications/zalo.desktop
  '';

  meta = {
    description = "Unofficial Zalo desktop client for Linux, repacked from the macOS app";
    homepage = "https://github.com/doandat943/zalo-for-linux";
    license = lib.licenses.unfree;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
    mainProgram = "zalo";
    platforms = [ "x86_64-linux" ];
  };
}
