(doom! :input ...
       :file-management ...
       :completion ...
       :ui ...
       :editor ...
       :emacs ...
       :term ...
       :tools ...
       :os ...
       :lang ...
       :email ...
       :app ...
       :config ...)
